### ISSUE TITLE
Metadatare per la diffusione online

### ISSUE THREAD

**Issue by aborruso** [ondata/dati-aperti-non-interessanti#2]
@avivace faccio una modifica e poi torno da te

Grazie

**Comment by aborruso** [comment]
Ciao @avivace e @mcortella ho fatto queste aggiunte:
- definito dei parametri di base in `_config.yml`
- in questo ho fissato l'utilizzo dello stile `pages-themes/primer`
- creata cartolina `images/dati_aperti_senza_interesse.png`
- creato un layout di default per aggiungere metadati e varie in `_layouts/default.html`

Che ve ne pare?

**Comment by mcortella** [comment]
Ciao @aborruso, per me va benissimo :)
Ho riletto e fatto due piccole correzioni, possiamo andare live per me.

**Comment by aborruso** [comment]
> Ho riletto e fatto due piccole correzioni, possiamo andare live per me.

mmm, occhio che io avevo inserito diverse proposte di modifica nella PR di stamattina https://github.com/ondata/dati-aperti-non-interessanti/pull/3

**Comment by mcortella** [comment]
> > Ho riletto e fatto due piccole correzioni, possiamo andare live per me.
> 
> mmm, occhio che io avevo inserito diverse proposte di modifica nella PR di stamattina #3

azz non l'avevo visto, sorry.

**Comment by avivace** [comment]
Si ci sarebbe solo da sistemare la frase che avete entrambi corretto (da qui il merge conflict sulla PR di @aborruso)

**Comment by aborruso** [comment]
ok, ho aggiornato tutto, lo trovate sempre qui:
https://ondata.github.io/dati-aperti-non-interessanti/

Che ve ne pare?

**Comment by mcortella** [comment]
Ottimo lavoro! E vedo già che stanno arrivando altre idee.

Grazie Andrea!

Il giorno lun 29 lug 2024 alle ore 19:18 Andrea Borruso <
***@***.***> ha scritto:
